concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "web-otus"
  url = "https://gitlab.home.lcl"
  id = 6
  token = "glrt-R286hbF2uXL6s2UfMiWY"
  token_obtained_at = 2024-11-14T13:37:44Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]