---
# tasks file for roles/rsyslog
- name: Install rsyslog
  apt:
    name:
    - rsyslog
    state: present
    
- name: Добавление информации в файл
  ansible.builtin.blockinfile:
    path: "/etc/rsyslog.conf"
    append_newline: true
    prepend_newline: true
    block: |
      # provides UDP syslog reception
      module(load="imudp")
      input(type="imudp" port="514")

      # provides TCP syslog reception
      module(load="imtcp")
      input(type="imtcp" port="514")
      #Add remote logs
      $template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
      *.* ?RemoteLogs
      & ~

    marker: "    # {mark} ANSIBLE MANAGED BLOCK"
  notify: Restart rsyslog