---
# tasks file for roles/bond
---
# tasks file for roles/vlan
- name: install software on Debian-based
  apt:
    name: 
      - vim
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true
  when: (ansible_os_family == "Debian")

- name: set up Bond
  template:
    src: bond.conf.j2
    dest: /etc/netplan/50-cloud-init.yaml 
    owner: root
    group: root
    mode: 0644

- name: apply set up vlan2
  shell: netplan apply
  become: true