global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Интервал сбора метрик, можно изменить при необходимости

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'web1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web1:9117']

  - job_name: 'web2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web2:9117']
  
  - job_name: 'web3'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web3:9117']