services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /mnt/otus/mysql-master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /mnt/otus/mysql-master/master_data:/var/lib/mysql
      - /mnt/otus/mysql-master/master-setup.sh:/docker-entrypoint-initdb.d/master-setup.sh
      - /mnt/otus/mysql-master/my.cnf:/etc/mysql/my.cnf 
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /mnt/otus/mysql-slave/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /mnt/otus/mysql-slave/slave_data:/var/lib/mysql
#      - /mnt/otus/mysql-slave/slave-setup.sh:/docker-entrypoint-initdb.d/slave-setup.sh
      - /mnt/otus/mysql-slave/my.cnf:/etc/mysql/my.cnf 
    depends_on:
      - mysql-master
    networks:
      - mysql_network
    ports:
      - "3307:3306"

networks:
  mysql_network:
