# tasks file for roles/postgres_install
---  
# Устанавливаем postgresql14-server
- name: install postgresql-server
  apt: 
    name: 
        - postgresql 
        - postgresql-contrib
    state: present
    update_cache: true
  
# Запускаем postgresql-14
- name: enable and start service
  service:
    name: postgresql
    state: started
    enabled: true