---
# tasks file for roles/dns-client
- name: Set resolv.conf on client
  template:
    src: client-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: copy rndc conf file
  copy: 
    src: rndc.conf 
    dest: /home/vagrant/rndc.conf 
    owner: vagrant 
    group: vagrant 
    mode: 0644

#Настройка сообщения при входе на сервер
- name: copy motd to the client
  copy: 
    src: client-motd 
    dest: /etc/motd 
    owner: root 
    group: root 
    mode: 0644