filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/containers/*/*.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    type: docker  # Название нашего сервиса
    service: docker

- type: log
  paths:
    - /var/log/*.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    type: host  # Название нашего сервиса
    service: host
output.logstash:
  hosts: ["logstash:5044"]