version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    restart: always
    #user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ports:
    #  - "9200:9200"
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "3"
    volumes:
      - /mnt/otus/elasticsearch/logs:/var/log/elasticsearch
      - /mnt/otus/elasticsearch/data:/var/lib/elasticsearch
      - /mnt/otus/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /mnt/otus/elasticsearch/certs:/usr/share/elasticsearch/config/certs
    networks:
      - caddy_network_acme

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #ports:
    #  - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /mnt/otus/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /mnt/otus/kibana/kibana_logs:/var/log/kibana
      - /mnt/otus/kibana/kibana_run:/run/kibana
    depends_on:
      - elasticsearch
    networks:
      - caddy_network_acme

  filebeat:
    image: elastic/filebeat:8.15.3
    container_name: filebeat
    restart: always
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /mnt/otus/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - LOGSTASH_HOSTS=logstash:5044  # Отправка логов в Logstash
    depends_on:
      - logstash
    networks:
      - caddy_network_acme

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    restart: always
    #environment:
    #  - xpack.monitoring.enabled=false
    ports:
      - "5044:5044"  # Порт для получения данных от Filebeat
      - "9600:9600"  # Порт для HTTP API Logstash
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "3"
    volumes:
      - /mnt/otus/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - caddy_network_acme

networks:
  caddy_network_acme: