networks:
  caddy_network_acme:
services:
  caddy_reverse_proxy:
    # Use the caddy:latest image from Docker Hub
    image: caddy:latest
    # Restart policy: restart the container unless explicitly stopped
    restart: always
    container_name: caddy_proxy
    # ports for Caddy
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
    volumes:
      # Mount the host Caddyfile
      - '/mnt/otus/caddy/Caddyfile:/etc/caddy/Caddyfile'
      - '/mnt/otus/caddy/caddy_data:/data'
      - '/mnt/otus/caddy/caddy_config:/config'
    # Connect the Caddy container caddy_net
    networks:
      - caddy_network_acme
